spring.application.name=agriculture-backendd
spring.datasource.url=jdbc:mysql://fsad-database-2.c2r0mekq4g6w.us-east-1.rds.amazonaws.com/fsad-db
spring.datasource.username=admin
spring.datasource.password=Hemanth1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080